version: '4'

services:
  jupyterhub: # The primary jupyterhub server
    build: jupyterhub
    image: jupyterhub_img
    container_name: jupyterhub
    ports:
      - "8000:8000"
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
      - ${PWD}/jupyterhub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
    environment:
      - DOCKER_JUPYTER_CONTAINER=jupyterlab_img
      - DOCKER_NOTEBOOK_DIR=/home/spawned/notebooks
    restart: on-failure

  jupyterlab: # Builds the image used when spawning new user instances
    build: jupyterlab
    image: jupyterlab_img

volumes:
  jupyterhub_data:
