version: '4'

services:
  jupyterhub:
    build: jupyterhub
    image: jupyterhub_img
    container_name: jupyterhub
    ports:
      - 8000:8000
    volumes:
      - /run/podman/podman.sock:/var/run/docker.sock
      - jupyterhub_data:/srv/jupyterhub
      - /etc/slurm:/etc/slurm
      - /usr/bin:/tmp/bin
    environment:
      - DOCKER_JUPYTER_CONTAINER=jupyterlab_img
      - DOCKER_NETWORK_NAME=${COMPOSE_PROJECT_NAME}_default
      - HUB_IP=jupyterhub
      - HOST
    restart: on-failure

  jupyterlab:
    build: jupyterlab
    image: jupyterlab_img
    container_name: jupyterlab-throwaway
    network_mode: none
    command: echo

volumes:
  jupyterhub_data:
