version: '4'

services:
  jupyterhub: # The primary jupyterhub server
    build: jupyterhub
    image: jupyterhub_img
    container_name: jupyterhub
    ports:
      - "8000:8000"
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
      - ${PWD}/jupyterhub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
    environment:
      - DOCKER_JUPYTER_CONTAINER=jupyter/tensorflow-notebook:hub-4.0.2
      - DOCKER_NOTEBOOK_DIR=/home/spawned/notebooks
      - DOCKER_NETWORK_NAME=jupyterhub-docker_default
    restart: on-failure

  jupyterlab: # Builds the image used when spawning new user instances
    image: jupyter/tensorflow-notebook:hub-4.0.2
    container_name: jupyterlab_img

volumes:
  jupyterhub_data:
