name: Publish Docker Images

on:
  release:
    types: [ "released" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Images

    strategy:
      fail-fast: false
      matrix:
        include:
          - image-dir: jupyterhub
            image-name: ghcr.io/${{ github.repository_owner }}/crc-jupyterhub

          - image-dir: jupyterlab
            image-name: ghcr.io/${{ github.repository_owner }}/crc-jupyterlab

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Get version
        run: |
          release_tag=${{ github.ref }}
          echo "version=${release_tag#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.image-dir }}
          push: true
          tags: ${{ matrix.image-name }}:${{ steps.version.outputs.version }}, ${{ matrix.image-name }}:latest
